export const Jobs = [
  "Software Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Fullstack Engineer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Data Engineer",
  "Data Analyst",
  "Data Scientist 2",
  "Machine Learning Engineer 2",
  "AI Engineer 2",
  "Product Manager",
  "Product Designer",
  "Product Owner",
  "Product Manager 2",
  "Product Owner 2",
];
